### ISSUE TITLE
Customize landing page and about pages

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/OpenOversight#2]
Pretty much lucyparsons/OpenOversight#784 - there's a bunch of stuff that points to LucyParsons that we should probably point to our own fork's information (and our twitter, etc.). A good example of what to change is the difference between openoversight.com and cops.photo.

**Comment by sarayourfriend** [comment]
Should we update all of the links to LPL's legal addresses too? Here's a list of references we may or may not want to change. I have no idea where to redirect some of them:

> OpenOversight is a <a href="https://lucyparsonslabs.com">Lucy Parsons Labs</a> project that aims to improve law enforcement...

We can probably keep that one as is, but we should add a blurb about our particular instance.

> Requests or questions regarding this project from those affiliated with law enforcement must be directed to our legal representation at <a href="mailto:legal@lucyparsonslabs.com">legal@lucyparsonslabs.com</a>.</p>

What should this be updated to?

> For media inquiries about OpenOversight, please email <a href="mailto:media@lucyparsonslabs.com">media@lucyparsonslabs.com</a>.

I don't think we want to field media inquiries about this but if so we should update this to our own information and then decide on a process for handling these requests?

> For other inquiries about the project, including collaboration, please contact <a href="mailto:openoversight@lucyparsonslabs.com">openoversight@lucyparsonslabs.com</a>.

This can probably be updated to our own information.

> A product of Lucy Parsons Labs in Chicago, IL. <br> <a href="https://lucyparsonslabs.com/" target="_blank" class="btn-unstyled">Lucy Parsons Labs</a><br>

Shall we leave this one? And then potentially add something like "Blah blah instance a project of Tech Bloc" with a link to the twitter?

> <a href="mailto:info@lucyparsonslabs.com"><i class="fa fa-envelope-square fa-3x social"></i></a><br>

The email button in the footer, we should update this to our own information

> <p><a href="mailto:info@lucyparsonslabs.com" class="btn btn-lg btn-primary" role="button">Mail us to get it enabled again</a></p>

Account disabled help message. Should definitely be updated to our own information.

```html
<h1>
    <small>Donate</small>
</h1>
<p>
    <!--TODO check on link + copy-->
    We are entirely volunteer funded and directed. Donations are greatly appreciated, and can be funded
    through PayPal, YouCaring, or Bitcoin.
    <br>
    Note: We are an IRS 501(c)3 not-for-profit and all donations are tax deductible!
</p>
<a class="btn btn-lg btn-secondary" href="https://lucyparsonslabs.com/support/" target="_blank">
    Donate
</a>
```

Should we just remove this? Or update it to a group cashapp/venmo/whatever?

```html
<b>A note to Illinois law enforcement</b>: This project does not perform facial recognition and is thus
in compliance with the Biometric Information Privacy Act. Requests or questions regarding this project
from those affiliated with law enforcement must be directed to our <a
        href="mailto:legal@lucyparsonslabs.com">legal representation</a>. You may also review our <a
        href="https://lucyparsonslabs.com/about/canary/" target="_blank">Warrant Canary</a>.
```

This seems like some heavy legal stuff, should we get some kind of lawyer involved to help with this?

**Comment by AetherUnbound** [comment]
I think you nailed it:
1. In general, areas where the project is described should also include "... This instance is run by Tech Bloc SEA" or something similar. https://docs.tech-bloc-sea.dev and https://cryptpad.fr are good examples of some changes we've done previously to this effect.
2. I think we can just remove the media one, but yea we'll want to add our own contact info
3. For legal stuff, I'd include the lucyparsonslab email (though we can remove the note for Illinois law enforcement I think)
4. Donation link can be removed as far as I'm concerned, maybe we can link to DivestSPD's donation link or something (since they source a lot of this info)
5. The social media stuff should either point at our socials, or (where they don't exist, e.g. Facebook) be removed

I think that covers everything? :open_mouth:

**Comment by sarayourfriend** [comment]
> For legal stuff, I'd include the lucyparsonslab email

Just to confirm that this is okay, the current language refers to the LPL email as "our legal representation" but I don't think that's actually legally accurate. Not sure what the implications of that are, if any.

**Comment by AetherUnbound** [comment]
> Just to confirm that this is okay, the current language refers to the LPL email as "our legal representation" but I don't think that's actually legally accurate. Not sure what the implications of that are, if any.

Ahh, yea that's true. Maybe "LPL's legal representation" instead of "our"? Like, I think having the legal info there is good, but yes it shouldn't be attributed as ours.
