### ISSUE TITLE
Direct uploads by volunteers to the officer page should not crop the image

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/OpenOversight#25]
Currently, all uploads are cropped to 300px on the largest side: https://github.com/SeattleDSA/OpenOversight/blob/a08396f62dc326210c6ba92b3e6914e3189ec97e/OpenOversight/app/main/views.py#L1094-L1098

For direct uploads to the officer's page, we should use the original image (not the cropped one).

I'm inclined to say that we should just not crop the images at all, but I'm open to some other thoughts there.

**Comment by sarayourfriend** [comment]
Closed by #30
